version: '3'

services:
  apache:
    image: httpd:2.4
    ports:
      - 80:80
    volumes:
      - ./www/:/var/www/html
      - ./hosts/my-httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./logs/httpd:/usr/local/apache2/logs
    depends_on:
      - php
  php:
    build:
      ./images/php
    volumes:
      - ./www:/var/www/html
      - ./logs/php:/var/log/apache2
    #   - ./images/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql
  mysql:
    image: mariadb
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
      - ./sql:/root
    environment:
      MYSQL_ROOT_PASSWORD: secret

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8765:80
    environment:  
      PMA_HOST: mysql
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: secret
    depends_on:
      - mysql
